CREATE TABLE ranktbl (
	rno INT(3) PRIMARY KEY NOT NULL,
	rname VARCHAR(10) NOT NULL,
	score INT(10)
);

CREATE TABLE playertbl (
	id VARCHAR(30) PRIMARY KEY NOT NULL,
	pw VARCHAR(30) NOT NULL,
	pname VARCHAR(10) NOT NULL,
	rate VARCHAR(10) NOT NULL
);