CREATE TABLE pList(
	pnum int(5) AUTO_INCREMENT PRIMARY KEY,
	pname VARCHAR(50) NOT NULL,
	userName VARCHAR(50) NOT NULL,
	price VARCHAR(50) NOT NULL,
	loaddate VARCHAR(50) NOT NULL,
	imgUrl VARCHAR(50) NOT NULL
);
