CREATE TABLE omok_user_regist(
	mno INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	id VARCHAR(100) NOT NULL,
	pw VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	regDate TIMESTAMP DEFAULT NOW()
);

CREATE TABLE omok_community_board(
	bno INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	writer VARCHAR(100) NOT NULL,
	create_Date VARCHAR(100) NOT NULL,
	content VARCHAR(1000) NOT NULL,
	recommend INT NOT NULL,
	views INT NOT NULL
);

CREATE TABLE omok_community_reply(
	rno INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	comment VARCHAR(100) NOT NULL,
	writer VARCHAR(100) NOT NULL,
	regDate TIMESTAMP DEFAULT NOW(),
	bno INT
);

CREATE TABLE omok_game_rooms(
	roomId INT(100) NOT NULL PRIMARY KEY,
	roomTitle VARCHAR(100) NOT NULL,
	roomPassword VARCHAR(100) NOT NULL,
	roomStatus VARCHAR(100) NOT NULL,
	createAt TIMESTAMP DEFAULT NOW(),
	updateAt TIMESTAMP,
	pno1 INT(100) NOT NULL,
	userId1 VARCHAR(100) NOT NULL,
	name1 VARCHAR(100)) NOT NULL,
	TIME1 INT(100) NOT NULL,
	x1 INT(100) NOT NULL,
	y1 INT(100) NOT NULL,
	turn1 INT(100) NOT NULL,
	pno2 INT(100) NOT NULL,
	userId2 VARCHAR(100) NOT NULL,
	name2 VARCHAR(100)) NOT NULL,
	TIME2 INT(100) NOT NULL,
	x2 INT(100) NOT NULL,
	y2 INT(100) NOT NULL,
	turn2 INT(100) NOT NULL,
);