CREATE TABLE bookReturn(
	c1 INT,
	c2 VARCHAR(10),
	c3 TIMESTAMP,
	c4 TIMESTAMP DEFAULT DATE_ADD(c3, INTERVAL 3 DAY)
);
INSERT INTO bookReturn(c1, c2, c3) VALUES (4, 'aaa', CURRENT_TIMESTAMP());
SELECT * FROM bookReturn;

DESC temp2;

CREATE TABLE temp2(
	c1 INT(11) NULL DEFAULT NULL,
	c2 VARCHAR(10) DEFAULT NULL,
	c3 TIMESTAMP NULL DEFAULT NULL,
	c4 TIMESTAMP NULL DEFAULT NULL
)

INSERT INTO temp2 (c1, c2)
VALUES (7, 'cli');

INSERT INTO temp2 (c1, c2, c3, c4)
VALUES (7, 'xxx', CURDATE(), DATE_ADD(c3, INTERVAL + 15 DAY));
SELECT * FROM temp2;